### ISSUE TITLE
Support multiple types of ugly

### ISSUE THREAD

**Issue by lgarron** [lgarron/ugly-http-extension#1]
- Dim / wash out (e.g. by lowering opacity)
- blur

Perhaps adapt some ideas from http://www.ex-parrot.com/pete/upside-down-ternet.html

**Comment by ericlaw1979** [comment]
Currently, the page is fully desaturated which makes some pages unusable; it might be nicer to use e.g. greyscale(85%) so that there's still a little bit of color, but everything feels dim and old.

MoarTLS does some of these (https://github.com/ericlaw1979/moartls/blob/master/injected.css). My favorites are turning images "bloody" (you do a sepia filter and color shift it toward red) and making them upside-down.

**Comment by lgarron** [comment]
> e.g. greyscale(85%) so that there's still a little bit of color, but everything feels dim and old.

Perhaps sepia while we're at it? ;-)
I did try changing opacity, which adds to the dimness.

I think it would be best to implement a few things (an options menu is trivial), and then pick a "default theme" that combines a few.

**Comment by lgarron** [comment]
Ooh, sepia:

![screen shot 2017-02-06 at 17 13 33](https://cloud.githubusercontent.com/assets/248078/22673518/9f3dbe1e-ec8f-11e6-9190-e2051038ec34.png)

**Comment by ericlaw1979** [comment]
Sepia is great for that appropriate "old timey" feel.

**Comment by lgarron** [comment]
> I think it would be best to implement a few things (an options menu is trivial), and then pick a "default theme" that combines a few.

Alright, I've changed my mind on this, since I'm not sure configurability is a desirable goal.

How's:

    filter: brightness(1.5) grayscale(0.8) !important;
    opacity: 0.75 !important;

**Comment by lgarron** [comment]
BAAHAHAHAHAHAHAHAHAH `hue-rotate(180deg)`:

![screen shot 2017-02-08 at 21 23 00](https://cloud.githubusercontent.com/assets/248078/22770387/e544534e-ee44-11e6-8ee9-acc4ae7ddd42.png)

**Comment by lgarron** [comment]
New themes!

`faded`
![screen shot 2017-02-08 at 21 35 37](https://cloud.githubusercontent.com/assets/248078/22770621/ab19efa6-ee46-11e6-9d00-e4123f34b38f.png)

`grayscale`
![screen shot 2017-02-08 at 21 35 43](https://cloud.githubusercontent.com/assets/248078/22770622/ab19fe06-ee46-11e6-9c90-84d9a2ab1f8c.png)

`sepia`
![screen shot 2017-02-08 at 21 35 49](https://cloud.githubusercontent.com/assets/248078/22770625/ab1d5aa6-ee46-11e6-9fbb-136c219f24c9.png)

`wide-blur`
![screen shot 2017-02-08 at 21 35 56](https://cloud.githubusercontent.com/assets/248078/22770623/ab1c76a4-ee46-11e6-95c8-535ac4492242.png)

`overexposed`
![screen shot 2017-02-08 at 21 36 02](https://cloud.githubusercontent.com/assets/248078/22770626/ab1e72e2-ee46-11e6-8c8f-816ddc10c608.png)

`flip-hue`
![screen shot 2017-02-08 at 21 36 07](https://cloud.githubusercontent.com/assets/248078/22770624/ab1cc082-ee46-11e6-9f6c-e45d0bf3e6d9.png)
