### ISSUE TITLE
Undo requires Javascript.

### ISSUE THREAD

**Issue by lgarron** [lgarron/ugly-http-extension#6]
I disable Javascript on HTTP in my work profile, which means `Undo` doesn't work for me as-is.

**Comment by ericlaw1979** [comment]
Disabling JavaScript also disables extensions' ability to use JavaScript in their isolated worlds? Crazy!

**Comment by lgarron** [comment]
`chrome.tabs` has `insertCSS`, but defers to the content script reference for general programmatic injection: https://developer.chrome.com/extensions/tabs#method-insertCSS

**Comment by lgarron** [comment]
So, it appears I tested wrong, and Javascript can run.

My guess is that I was testing without 00a0fc0, so which @ericlaw1979 accidentally [forgot to include in the `Makefile`](https://github.com/lgarron/ugly-http-extension/pull/5#issuecomment-277932421). :-P
