### ISSUE TITLE
Brightness filter makes text harder to read

### ISSUE THREAD

**Issue by jonathanKingston** [lgarron/ugly-http-extension#7]
Now the extension uses opacity, perhaps consider removing the brightness?

Change:
```
body:not(.escape-httpugly) {
    filter: brightness(1.5) grayscale(0.85) !important;
    opacity: 0.75 !important;
}
```
To use
```
    filter: grayscale(0.85) !important;
```

The bottom window is the existing code in this screenshot:
![selection_482](https://cloud.githubusercontent.com/assets/338988/22697103/50987970-ed48-11e6-9d22-31b192858923.png)

**Comment by ericlaw1979** [comment]
Similar issue here: http://serverfault.com/questions/410240/is-there-a-windows-command-line-utility-to-verify-user-credentials makes it almost unusable. I thought it was pretty great with just 85% grayscale-- does opacity and brightness solve anything?

**Comment by jonathanKingston** [comment]
Opacity solves the contrast issue where colour has meaning on the page I think.

**Comment by lgarron** [comment]
Yeah, opacity and brightness are my attempt to tone down contrast for very dark/bright areas.

Grayscale for http://serverfault.com/questions/410240/is-there-a-windows-command-line-utility-to-verify-user-credentials

I'll get rid of brightness for now. If someone knows how to use a filter clamp/curve darkness from 0%-100% to, say, 20%-80%, that would be useful.

**Comment by jonathanKingston** [comment]
Currently can't test on serverfault etc due to this bug:
  https://bugzilla.mozilla.org/show_bug.cgi?id=1336480

However jsbin.com and natwest.com look the same or better(and closer to I think what you are after) with this:
```
filter: saturate(300%) opacity(75%) grayscale(85%) contrast(95%);
```
Removing the opacity rule too.

I also like the look of:
```
filter: saturate(305%) opacity(85%) grayscale(93%) contrast(91%) hue-rotate(56deg);
```

Interestingly there appears to be a bug for contrast in both Chrome and Firefox in that it treats background of body different to elements further down the DOM tree, so white background elements appear to be darker than the body background of white.

**Comment by lgarron** [comment]
> filter: saturate(300%) opacity(75%) grayscale(85%) contrast(95%);

I've adapted this (without saturation) for the `faded` theme.
